[app]
demo_mode = false

[firebase.config]
apiKey = "AIzaSyAIsB13o2XN10aKWMOIK1mkiAE_0TncCwc"
authDomain = "churniq-58fc3.firebaseapp.com"
projectId = "churniq-58fc3"
storageBucket = "churniq-58fc3.firebasestorage.app"
messagingSenderId = "96546088868"
appId = "1:96546088868:web:9a3e6cbb4bc17783c24331"

[gemini]
api_key = "AIzaSyBtFICyU843miFk8s64gIzPZMZBhDaXrwA"

[email]
sender_email = "your-email@gmail.com"
smtp_server = "smtp.gmail.com"
smtp_port = 465
smtp_username = "your-email@gmail.com"
smtp_password = "your-app-password"
use_ssl = true
